In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

In [2]:
samp = 10**6
mu_S = 5
std_S = 2
S = np.random.normal(mu_S, std_S, (samp,1))


bins = 15
cm = 1/2.54  # centimeters in inches
plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams["font.size"] = 9
fig1, ax1 = plt.subplots(1, figsize=(6*cm, 6*cm), sharey='row', dpi=80, facecolor='w', edgecolor='k')
plt.subplots_adjust(left=0.22, right=.98, top=0.98, bottom=0.1)
ax1.hist(S,bins)

<IPython.core.display.Javascript object>

(array([2.20000e+01, 1.68000e+02, 1.58800e+03, 9.01200e+03, 3.64240e+04,
        1.00495e+05, 1.88744e+05, 2.43554e+05, 2.15523e+05, 1.31097e+05,
        5.42230e+04, 1.56890e+04, 3.00100e+03, 4.12000e+02, 4.80000e+01]),
 array([-4.58850777, -3.33979103, -2.09107428, -0.84235754,  0.40635921,
         1.65507595,  2.90379269,  4.15250944,  5.40122618,  6.64994293,
         7.89865967,  9.14737642, 10.39609316, 11.64480991, 12.89352665,
        14.14224339]),
 <a list of 15 Patch objects>)

In [3]:
S_norm = (S-mu_S)/std_S

In [4]:
fig2, ax2 = plt.subplots(1, figsize=(6*cm, 6*cm), sharey='row', dpi=80, facecolor='w', edgecolor='k')
plt.subplots_adjust(left=0.22, right=.98, top=0.98, bottom=0.1)
ax2.hist(S_norm,bins)


<IPython.core.display.Javascript object>

(array([2.20000e+01, 1.68000e+02, 1.58800e+03, 9.01200e+03, 3.64240e+04,
        1.00495e+05, 1.88744e+05, 2.43554e+05, 2.15523e+05, 1.31097e+05,
        5.42230e+04, 1.56890e+04, 3.00100e+03, 4.12000e+02, 4.80000e+01]),
 array([-4.79425389, -4.16989551, -3.54553714, -2.92117877, -2.2968204 ,
        -1.67246203, -1.04810365, -0.42374528,  0.20061309,  0.82497146,
         1.44932984,  2.07368821,  2.69804658,  3.32240495,  3.94676333,
         4.5711217 ]),
 <a list of 15 Patch objects>)